const $ = (s) => document.querySelector(s), dialog = $('#new-dialog');
let projectId = Number(localStorage.getItem('novel_project_id')) || 1, currentView = 'overview', resourceType = '', dirtyWriter = false, writerSaveTimer = null;
const labels = { project:['小说项目','','','小说名称','例如：未命名的星港','一句话简介'], world:['世界设定','类别','例如：核心设定','名称','例如：星港公约','描述'], character:['角色','角色定位','例如：主角','姓名','例如：林澈','性格 / 目标'], location:['地点','','','地点名称','例如：第七码头','描述'], item:['道具','','','道具名称','例如：潮汐引擎','描述'] };
function formatWords(v){return Number(v||0).toLocaleString('en-US')}
function installProjectPicker(){const root=$('.project-switch');if(!root||root.querySelector('select'))return;root.innerHTML='当前项目：<select id="project-picker" aria-label="切换当前小说"></select>';root.querySelector('select').addEventListener('change',e=>{projectId=Number(e.target.value);localStorage.setItem('novel_project_id',String(projectId));loadAll()})}
if(localStorage.getItem('novel_token')&&!localStorage.getItem('novel_auth_v1'))localStorage.removeItem('novel_token');
function installAuth(){const forceLogin=new URLSearchParams(location.search).has('login');if(document.querySelector('.auth-screen'))return;if(localStorage.getItem('novel_token')&&!forceLogin)return;document.body.insertAdjacentHTML('beforeend','<div class="auth-screen"><div class="auth-card"><div class="brand"><span class="brand-mark">N</span><span>Novel <em>studio</em></span></div><div class="mini-label">WELCOME BACK</div><h1 id="auth-title">登录创作空间</h1><p>继续你的故事，让每一章都有下一步。</p><form id="auth-form"><label>邮箱或用户名<input name="account" required placeholder="author@example.com"></label><label>密码<input name="password" type="password" required placeholder="至少 6 位密码"></label><button class="primary" type="submit" id="auth-submit">登录</button></form><button class="auth-switch" id="auth-switch">还没有账号？注册新作者</button><small id="auth-message"></small></div></div>');let register=false;$('#auth-switch').onclick=()=>{register=!register;$('#auth-title').textContent=register?'创建作者账号':'登录创作空间';$('#auth-submit').textContent=register?'注册':'登录';$('#auth-switch').textContent=register?'已有账号？返回登录':'还没有账号？注册新作者'};$('#auth-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const endpoint=register?'/api/auth/register':'/api/auth/login';try{const r=await api(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({account:fd.get('account'),password:fd.get('password')})});localStorage.setItem('novel_token',r.token);history.replaceState({},'',location.pathname);$('.auth-screen').remove();loadAll()}catch(err){$('#auth-message').textContent='登录失败，请检查服务是否启动'}}}
installAuth();
document.addEventListener('submit',()=>setTimeout(()=>{if(localStorage.getItem('novel_token'))localStorage.setItem('novel_auth_v1','1')},50));
if(!document.querySelector('[data-logout]'))$('.top-actions')?.insertAdjacentHTML('beforeend','<button class="logout" data-logout>退出登录</button>');
document.addEventListener('click',e=>{if(e.target.closest('[data-logout]')){localStorage.removeItem('novel_token');localStorage.removeItem('novel_auth_v1');location.replace('/?login=1')}});
function renderProject(p){projectId=p.id;localStorage.setItem('novel_project_id',String(p.id));if($('#current-project'))$('#current-project').textContent=p.title;if($('#project-picker'))$('#project-picker').value=String(p.id);$('#project-title').textContent=p.title;$('#project-summary').textContent=p.summary||'还没有简介，给这本小说留下一句话吧。';$('#word-count').textContent=formatWords(p.current_words)}
function renderChapters(list){$('#empty-chapters').style.display=list.length?'none':'block'; $('#chapters').innerHTML=list.map(c=>`<div class="chapter-row"><span class="num">${String(c.number).padStart(3,'0')}</span><div><strong>${c.title}</strong><small>${c.outline||'暂无大纲'}</small></div><span>${formatWords(c.word_count)}</span><span class="badge ${c.status==='done'?'':'outline'}">${statusText(c.status)}</span><small>${new Date(c.updated_at).toLocaleDateString('zh-CN')}</small></div>`).join(''); $('#chapter-count').textContent=list.length; $('#chapter-board').innerHTML=list.map(c=>`<article class="board-card"><div class="card-heading"><span class="num">第 ${c.number} 章</span><span class="badge ${c.status==='done'?'':'outline'}">${statusText(c.status)}</span></div><h3>${c.title}</h3><p>${c.outline||'暂无章节摘要，先补充这一章要发生什么。'}</p><div class="board-meta"><span>${formatWords(c.word_count)} 字</span><select data-chapter="${c.id}"><option value="outline" ${c.status==='outline'?'selected':''}>规划中</option><option value="writing" ${c.status==='writing'?'selected':''}>写作中</option><option value="review" ${c.status==='review'?'selected':''}>待审核</option><option value="done" ${c.status==='done'?'selected':''}>已完成</option></select><button data-writer="${c.id}">写正文</button><button data-chapter-edit="${c.id}">编辑</button><button data-chapter-move="${c.id}">移动</button><button data-chapter-delete="${c.id}">删除</button></div></article>`).join(''); document.querySelectorAll('[data-chapter]').forEach(x=>x.onchange=()=>updateChapter(x.dataset.chapter,{status:x.value}));}
function statusText(s){return ({done:'已完成',writing:'写作中',review:'待审核',outline:'规划中'})[s]||'未开始'}
function renderResources(type,list){const root=$('#'+type+'-list');const path=type==='world'?'world':type+'s';root.innerHTML=list.length?list.map(x=>{const title=x.name,detail=type==='character'?(x.role||'未设定')+' · '+(x.personality||x.goal||'等待补充角色档案'):x.description||'还没有描述';return '<article class="resource-card" data-resource-type="'+type+'" data-resource-id="'+x.id+'"><div class="resource-icon">'+(type==='character'?'人':type==='world'?'设':type==='location'?'地':'物')+'</div><div><div class="mini-label">'+(type==='world'?(x.category||'未分类'):type==='character'?'角色档案':type==='location'?'场景档案':'道具档案')+'</div><h3>'+title+'</h3><p>'+detail+'</p><div class="resource-actions"><button data-resource-edit>编辑</button><button data-resource-delete>删除</button></div></div></article>'}).join(''):'<div class="empty-card">还没有内容，点击右上角新增第一条记录。</div>'}
async function api(path,opts={}){const headers=new Headers(opts.headers||{});const token=localStorage.getItem('novel_token');if(token)headers.set('Authorization',`Bearer ${token}`);if(opts.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const r=await fetch(path,{...opts,headers});if(r.status===401&&!path.startsWith('/api/auth/')){localStorage.removeItem('novel_token');localStorage.removeItem('novel_auth_v1');if(new URLSearchParams(location.search).has('login')){installAuth()}else{location.replace('/?login=1')}throw new Error('请先登录')}if(!r.ok) throw new Error(await r.text());return r.json()}
function installWorkflowPages(){const nav=$('.topbar nav');if(nav&&!nav.querySelector('[data-view="analysis"]'))nav.insertAdjacentHTML('beforeend','<a data-view="analysis">分析中心</a><a data-view="export">导出发布</a>');const side=$('.sidebar .side-footer');if(side&&!document.querySelector('.sidebar [data-view="analysis"]'))side.insertAdjacentHTML('beforebegin','<button class="nav-item" data-view="analysis">◒ <span>分析中心</span></button><button class="nav-item" data-view="export">⇧ <span>导出发布</span></button>');if(!document.querySelector('[data-page="analysis"]'))$('.content').insertAdjacentHTML('beforeend','<section class="view hidden" data-page="analysis"><div class="page-heading"><div><div class="eyebrow">PROJECT INSIGHTS</div><h1>分析中心</h1><p>用真实的创作数据回看作品推进情况。</p></div><button class="primary" data-action="refresh-analysis">刷新分析</button></div><div class="analysis-grid" id="analysis-grid"></div></section><section class="view hidden" data-page="export"><div class="page-heading"><div><div class="eyebrow">PUBLISH</div><h1>导出发布</h1><p>把当前项目整理成可继续编辑或发布的文稿。</p></div></div><div class="export-card card"><h2>导出当前小说</h2><p>包含项目标题、章节标题和正文内容；没有正文的章节会导出章节大纲。</p><div class="export-actions"><button data-export="md">下载 Markdown</button><button data-export="txt">下载 TXT</button></div></div></section>');if($('[data-page="world"] .page-heading')&&!$('[data-page="world"] .page-heading [data-action="generate-world"]'))$('[data-page="world"] .page-heading').insertAdjacentHTML('beforeend','<button data-action="generate-world">✦ AI 生成设定</button>');if($('[data-page="characters"] .page-heading')&&!$('[data-page="characters"] .page-heading [data-action="generate-characters"]'))$('[data-page="characters"] .page-heading').insertAdjacentHTML('beforeend','<button data-action="generate-characters">✦ AI 生成人物</button>')}
async function loadAnalysis(){try{const a=await api(`/api/projects/${projectId}/analysis`),tasks=await api(`/api/projects/${projectId}/tasks`);$('#analysis-grid').innerHTML=[['总字数',formatWords(a.word_count),'所有章节'],['章节完成度',`${a.completion_rate}%`,`${a.completed_chapters}/${a.chapters} 章已完成`],['角色档案',a.characters,'已登记角色'],['世界设定',a.world_settings,'已登记设定']].map(x=>`<article class="analysis-card card"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></article>`).join('')+`<article class="task-history card"><div class="card-heading"><h3>最近 AI 任务</h3><span>${tasks.length} 条</span></div>${tasks.length?tasks.slice().reverse().slice(0,6).map(t=>`<div class="task-row"><span>${t.type}</span><b class="task-${t.status}">${t.status==='completed'?'已完成':t.status==='running'?'进行中':'失败'} ${t.progress}%</b><small>${t.result||'等待结果'}</small></div>`).join(''):'<p>还没有 AI 任务，去章节规划开始生成。</p>'}</article>`}catch(e){console.warn(e)}}
installWorkflowPages();
installProjectPicker();
async function loadAll(){try{const ps=await api('/api/projects');const active=ps.find(p=>p.id===projectId)||ps[0];if(active){projectId=active.id;if($('#project-picker'))$('#project-picker').innerHTML=ps.map(p=>'<option value="'+p.id+'">'+p.title+'</option>').join('');renderProject(active); const [cs,w,ch,l,i]=await Promise.all([api(`/api/projects/${projectId}/chapters`),api(`/api/projects/${projectId}/world`),api(`/api/projects/${projectId}/characters`),api(`/api/projects/${projectId}/locations`),api(`/api/projects/${projectId}/items`)]); renderChapters(cs); renderResources('world',w); renderResources('character',ch); renderResources('location',l); renderResources('item',i); $('#character-count').textContent=ch.length}}catch(e){console.warn('API 请求失败',e);if(e.message==='请先登录')installAuth()}}
function showView(view){currentView=view; document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('hidden',x.dataset.page!==view)); document.querySelectorAll('[data-view]').forEach(x=>{x.classList.toggle('active',x.dataset.view===view);x.classList.toggle('selected',x.dataset.view===view)});}
function openDialog(type){resourceType=type; const isChapter=type==='chapter'; $('#dialog-kicker').textContent=isChapter?'NEW CHAPTER':type==='project'?'NEW PROJECT':'STORY BIBLE'; $('#dialog-title').textContent=isChapter?'新建章节':type==='project'?'创建一本新小说':`新增${labels[type][0]}`; let fields=''; if(type==='project') fields='<label>小说名称<input name="name" required placeholder="例如：未命名的星港"></label><label>一句话简介<textarea name="description" placeholder="主角、冲突和故事发生在哪里？"></textarea></label>'; else if(type==='character') fields='<label>姓名<input name="name" required placeholder="例如：林澈"></label><label>性格 / 目标<textarea name="description" placeholder="性格、动机和目标"></textarea></label>'; else fields=`<label>${isChapter?'章节标题':type==='world'?'设定名称':type==='location'?'地点名称':'道具名称'}<input name="name" required placeholder="${isChapter?'例如：穿过雾区':type==='world'?'例如：星港公约':type==='location'?'例如：第七码头':'例如：潮汐引擎'}"></label><label>${isChapter?'剧情摘要':'描述'}<textarea name="description" placeholder="${isChapter?'这一章要发生什么？':'补充这条资料的细节'}"></textarea></label>`; $('#dialog-fields').innerHTML=fields; dialog.showModal()}
document.addEventListener('click',e=>{const writer=e.target.closest('[data-writer]'); if(writer) editChapter(writer.dataset.writer); const v=e.target.closest('[data-view]'); if(v){showView(v.dataset.view);if(v.dataset.view==='analysis')loadAnalysis()} const ex=e.target.closest('[data-export]');if(ex)window.location.href=`/api/projects/${projectId}/export?format=${ex.dataset.export}`; const a=e.target.closest('[data-action]'); if(a){if(a.dataset.action==='new')openDialog('project'); else if(a.dataset.action==='new-chapter')openDialog('chapter'); else if(a.dataset.action==='generate-outline')generateOutline(); else if(a.dataset.action==='generate-world')generateResource('world'); else if(a.dataset.action==='generate-characters')generateResource('characters'); else if(a.dataset.action==='refresh-analysis')loadAnalysis(); else openDialog(a.dataset.action)}});
$('#new-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target), name=fd.get('name'), description=fd.get('description'); try{if(resourceType==='project'){const created=await api('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:name,summary:description,genre:'科幻',target_words:100000})});projectId=created.id;localStorage.setItem('novel_project_id',String(projectId))}else if(resourceType==='chapter'){await api(`/api/projects/${projectId}/chapters`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:name,outline:description,status:'outline'})})}else{const body=resourceType==='world'?{category:'未分类',name,description}:resourceType==='character'?{name,role:'待设定',personality:description,goal:''}:{name,description}; await api(`/api/projects/${projectId}/${resourceType==='world'?'world':resourceType+'s'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}dialog.close();e.target.reset();await loadAll(); if(resourceType==='chapter')showView('chapters')}catch(err){console.error(err);alert('保存失败：'+(err.message||'请检查服务和登录状态'))}});
async function updateChapter(id,body){await api(`/api/chapters/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});loadAll()}
async function editChapter(id){const c=await api(`/api/chapters/${id}`); let box=$('#writer-dialog'); if(!box){document.body.insertAdjacentHTML('beforeend','<dialog id="writer-dialog"><div class="writer-head"><div><div class="mini-label">DRAFT EDITOR</div><h2 id="writer-heading"></h2></div><button class="close" data-close-writer>×</button></div><div class="writer-body"><textarea id="writer-editor" placeholder="从这里开始写正文……"></textarea><div id="writer-versions" class="writer-versions"></div><div class="writer-actions"><span id="writer-count">0 字</span><span id="writer-message">已加载</span><button data-writer-check>一致性检查</button><button data-writer-ai="generate">✦ 生成正文</button><button data-writer-ai="continue">续写</button><button data-writer-ai="rewrite">润色</button><button class="primary" data-save-writer>保存正文</button></div></div></dialog>');box=$('#writer-dialog')} $('#writer-heading').textContent=`第 ${c.number} 章 · ${c.title}`; $('#writer-editor').value=c.content||''; $('#writer-count').textContent=`${[...(c.content||'')].length} 字`; box.dataset.chapter=id; box.showModal(); loadVersions(id); $('#writer-editor').oninput=()=>$('#writer-count').textContent=`${[...$('#writer-editor').value].length} 字`}
async function saveWriter(silent=false){const id=$('#writer-dialog').dataset.chapter,content=$('#writer-editor').value;await updateChapter(id,{content,status:'writing',word_count:[...content].length});dirtyWriter=false;$('#writer-message').textContent=silent?'已自动保存':'已保存';}
async function loadVersions(id){const list=await api(`/api/chapters/${id}/versions`);$('#writer-versions').innerHTML=list.length?`<label>历史版本 <select id="version-select"><option value="">选择版本</option>${list.slice().reverse().map(v=>`<option value="${v.id}">${new Date(v.created_at).toLocaleString('zh-CN')} · ${v.source} · ${v.word_count} 字</option>`).join('')}</select></label><button data-restore-version>恢复选中版本</button><div id="version-preview"></div>`:'<span>暂无历史版本，保存正文后会自动记录。</span>';if(list.length){$('#version-select').onchange=()=>previewVersion(list,$('#version-select').value)}}
function previewVersion(list,id){const v=list.find(x=>String(x.id)===String(id));$('#version-preview').textContent=v?`版本预览：\n${v.content}`:''}
async function writerAI(kind){const id=$('#writer-dialog').dataset.chapter;$('#writer-message').textContent='AI 正在处理…';const task=await api(`/api/chapters/${id}/${kind}`,{method:'POST'});streamTask(task.id,t=>{if(kind==='generate'||kind==='continue'){$('#writer-editor').value=($('#writer-editor').value?$('#writer-editor').value+'\n\n':'')+t.result}else if(kind==='rewrite'){$('#writer-editor').value=t.result}$('#writer-editor').dispatchEvent(new Event('input'));$('#writer-message').textContent='AI 已完成，请检查后保存'})}
document.addEventListener('click',e=>{if(e.target.closest('[data-close-writer]'))$('#writer-dialog').close();if(e.target.closest('[data-save-writer]'))saveWriter();const ai=e.target.closest('[data-writer-ai]');if(ai)writerAI(ai.dataset.writerAi)});
document.addEventListener('click',async e=>{const check=e.target.closest('[data-writer-check]');if(check){const id=$('#writer-dialog').dataset.chapter;const r=await api(`/api/chapters/${id}/check`,{method:'POST'});$('#writer-message').textContent=r.warnings.length?`发现 ${r.warnings.length} 个问题`:'一致性检查通过';alert(r.warnings.length?r.warnings.join('\n'):'检查通过，暂未发现角色一致性问题。')}});
document.addEventListener('click',async e=>{if(e.target.closest('[data-restore-version]')){const version=$('#version-select').value;if(!version){alert('请先选择一个版本');return}if(!confirm('恢复前会保留当前内容，确定恢复吗？'))return;const id=$('#writer-dialog').dataset.chapter;const c=await api(`/api/chapters/${id}/versions/${version}/restore`,{method:'POST'});$('#writer-editor').value=c.content||'';$('#writer-editor').dispatchEvent(new Event('input'));$('#writer-message').textContent='版本已恢复';loadVersions(id)}});
async function generateOutline(){try{const task=await api(`/api/projects/${projectId}/generate/outline`,{method:'POST'});alert(`AI 大纲任务已开始（任务 #${task.id}），请稍后查看结果。`);streamTask(task.id,t=>{alert(`AI 生成完成：\n${t.result}`);loadAll()})}catch(e){alert('AI 服务暂不可用')}}
async function generateResource(kind){try{const task=await api(`/api/projects/${projectId}/generate/${kind}`,{method:'POST'});alert(`AI 任务已开始（任务 #${task.id}），完成后会写入当前项目。`);streamTask(task.id,async()=>{await loadAll();alert('AI 生成完成，内容已写入项目。')})}catch(e){alert('AI 服务暂不可用')}}
function streamTask(id,onDone){const source=new EventSource(`/api/tasks/${id}/stream`);let finished=false;source.onmessage=e=>{const task=JSON.parse(e.data);if(task.status==='completed'||task.status==='failed'){finished=true;source.close();if(task.status==='completed')onDone(task);else $('#writer-message')&&($('#writer-message').textContent='AI 任务失败')}};source.onerror=async()=>{source.close();if(finished)return;try{const task=await api(`/api/tasks/${id}`);if(task.status==='completed'){finished=true;onDone(task)}else if(task.status==='failed'){finished=true;$('#writer-message')&&($('#writer-message').textContent='AI 任务失败')}else{setTimeout(()=>streamTask(id,onDone),1000)}}catch(e){$('#writer-message')&&($('#writer-message').textContent='AI 连接中断，请稍后重试')}}}
document.addEventListener('click',async e=>{const card=e.target.closest('[data-resource-type]');if(!card)return;const type=card.dataset.resourceType,id=card.dataset.resourceId,path=type==='world'?'world':type+'s';if(e.target.closest('[data-resource-delete]')){if(!confirm('确定删除这条记录吗？'))return;await api('/api/projects/'+projectId+'/'+path+'/'+id,{method:'DELETE'});await loadAll();return}if(e.target.closest('[data-resource-edit]')){const name=prompt('名称');if(name===null||!name.trim())return;const description=prompt('描述');if(description===null)return;let body={name:name.trim(),description};if(type==='world')body.category='未分类';if(type==='character')body={name:name.trim(),role:'待设定',personality:description,goal:''};await api('/api/projects/'+projectId+'/'+path+'/'+id,{method:'PUT',body:JSON.stringify(body)});await loadAll()}})
document.addEventListener('click',async e=>{const del=e.target.closest('[data-chapter-delete]');if(del){if(!confirm('确定删除这一章吗？'))return;await api('/api/chapters/'+del.dataset.chapterDelete,{method:'DELETE'});await loadAll();return}const move=e.target.closest('[data-chapter-move]');if(move){const to=prompt('移动到第几章？');if(to===null)return;const n=Number(to);if(!Number.isInteger(n)||n<1){alert('请输入正确的章节序号');return}await api('/api/chapters/'+move.dataset.chapterMove+'/move',{method:'POST',body:JSON.stringify({to_number:n})});await loadAll();return}const edit=e.target.closest('[data-chapter-edit]');if(edit){const id=edit.dataset.chapterEdit;const title=prompt('章节标题');if(title===null||!title.trim())return;const outline=prompt('剧情摘要（可留空）');if(outline===null)return;await api('/api/chapters/'+id,{method:'PATCH',body:JSON.stringify({title:title.trim(),outline})});await loadAll()}})
document.addEventListener('input',e=>{if(e.target.id==='writer-editor'){dirtyWriter=true;clearTimeout(writerSaveTimer);writerSaveTimer=setTimeout(()=>saveWriter(true),1200)}});
loadAll();
